# Generated by Django 5.2.1 on 2025-05-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(help_text='Identificador único del vuelo/unidad', max_length=100, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, help_text='Altitud en metros o pies, según la API', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Velocidad', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Rumbo en grados', null=True)),
                ('timestamp', models.DateTimeField(help_text='Fecha y hora de la última actualización de esta posición')),
                ('raw_data', models.JSONField(blank=True, help_text='Datos crudos de la API para este vuelo', null=True)),
                ('last_updated_by_system', models.DateTimeField(auto_now=True, help_text='Cuándo se actualizó este registro en nuestra BD')),
            ],
            options={
                'verbose_name': 'Flight Data',
                'verbose_name_plural': 'Flight Data',
                'ordering': ['-timestamp'],
            },
        ),
    ]
